### ISSUE TITLE
Make a2a transports defined per relationship instead of globally

### ISSUE THREAD

**Issue by nrempel** [bcgov/indy-catalyst#11]

**Comment by swcurran** [comment]
Shouldn't the selection of transport be picked up from the endpoint of the Agent?  An agent tells another agent that will directly message it to use a specified endpoint. From that, the sending agent knows what transport to use.

My concern is that it shouldn't be per relationship, but on the endpoint used by the agent in the relationship.  For example, an agent might say "use this DID" as an endpoint, and the sending agent would have to resolve the DID to get the actual endpoint, and hence the transport.
