### ISSUE TITLE
Provide a flag for running the Indy Catalyst and/or UI in AgentBook mode - view only

### ISSUE THREAD

**Issue by swcurran** [bcgov/indy-catalyst#124]
Add a startup flag on either Indy Catalyst or the UI and use it to make the following changes to the Agent handling.  As well, add a way to pass in a URL for an instruction link (it will be to a github MD page).

If the flag for running as AgentBook is set:

* Automatically respond to invitation requests with invitation acceptances
* On receiving a message, return "Message received" as a response basic message
* Grey out the "Receive Invitation" button.
* After clicking Done on the "Generate Invite" screen, go to the Connections Details screen for that connection.

The following could be done whether or not the flag is there.

* Add a "Copy" button beside messages received from the Agent.  We'll use this to copy the text of an Invitation.
* Wrap or truncate the text of a long message - e.g. an invitation

Additional requests:

We have a challenge with the invite being posted. Once it's posted, it should only be used once. Can you add a mechanism so that when the user clicks "Copy" button (to be added per existing Zenhub), you someone mark the invitation as "Used", so others won't try to use it?

For bonus marks - on the main screen list of connections, keep a count of "Unused Invitations" beside the messages count.

**Comment by swcurran** [comment]
New item added to this ticket:

> After clicking Done on the "Generate Invite" screen, go to the Connections Details screen for that connection.

**Comment by cywolf** [comment]
There are a few new flags supported:

- `--accept-invites` to auto-accept invitations
- `--accept-requests` to auto-accept connection requests
- `--no-receive-invites` to disable receiving invites through the admin UI
- `--auto-respond-messages` to reply to all basic messages
