### ISSUE TITLE
Set up testing automation with github

### ISSUE THREAD

**Issue by nrempel** [bcgov/indy-catalyst#13]
lint
run tests
code coverage
run automatic code formatter

**Comment by nrempel** [comment]
@WadeBarnes 

CircleCI can probably be used to run tests and lint check: https://github.com/marketplace/circleci for running tests

Codecoverage - we can use https://github.com/marketplace/codecov

https://hub.codebeat.co/docs/github-pull-requests might be helpful as well

https://github.com/Mariatta/black_out could be used (maybe?) to automatically format the python code when a pull request is opened

I think the first two are required and the last two are nice-to-have's. (codebeat should be one click to enable)

I'm happy to work on the details if you do the admin requirements

**Comment by nrempel** [comment]
Read the docs might make sense in here as well. I'm not familiar with the current docs build process.

**Comment by nrempel** [comment]
Hey @WadeBarnes just wondering if you had a chance to take a look at this?

It would be beneficial to have this kind of thing if we think we might see external contributors soon.

If you're able to add the github integrations, then I'm happy to configure the service if you can give me access.

**Comment by WadeBarnes** [comment]
@nremple, I should be able to start looking at this tomorrow.

**Comment by nrempel** [comment]
Great thanks,

I think enabling these two github integrations should be a good start:

https://github.com/marketplace/circleci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW45MA==#pricing-and-setup

https://github.com/marketplace/codecov/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xNg==#pricing-and-setup

**Comment by WadeBarnes** [comment]
CircleCI; https://circleci.com/gh/bcgov/indy-catalyst

Codecov; https://codecov.io/gh/bcgov/indy-catalyst
