### ISSUE TITLE
Documentation cleanup of references to "TheOrgBook" and repos

### ISSUE THREAD

**Issue by esune** [bcgov/indy-catalyst#229]
The README files in the `indy-catalyst` repo still contain references to the `TheOrgBook` GitHub repository.

These references should be updated to be self-contained to the `indy-catalyst` repository.

**Comment by seanadipose** [comment]
Removed a number of references to the orgbook. Some are still remaining in the server documentation (I haven't updated the documentation located in starter-kits\credential-registry\server\tob-api yet, I'll take care of that after I've run through a bit more work in ICOB to ensure that documentation is still relevant)

The preivew README.md contains a reference to Visual Studio 2017.

**Comment by WadeBarnes** [comment]
@seanadipose, any Visual Studio 2017 references can be removed.  We should clean up any related project files too.  We have not used Visual Studio 2017 for active development on the project in a long time.
