### ISSUE TITLE
Implement persistent outbound message queue and queue management messages

### ISSUE THREAD

**Issue by andrewwhitehead** [bcgov/indy-catalyst#239]
A draft spec for queue management message family exists and may need to be submitted as an RFC first.

**Comment by swcurran** [comment]
@andrewwhitehead - what is the status of this?  Close as no longer relevant?  Move to ACA-Py?

**Comment by swcurran** [comment]
Closing this as other OBE or already implemented. Please reopen if this is still relevant.
