### ISSUE TITLE
Add API version to request headers

### ISSUE THREAD

**Issue by esune** [bcgov/indy-catalyst#260]
See: https://www.django-rest-framework.org/api-guide/versioning/

BCGov API guidelines: https://github.com/bcgov/api-guidelines

**Comment by ianco** [comment]
Investigate how to integrate Django versioning:

https://www.django-rest-framework.org/api-guide/versioning/

**Comment by ianco** [comment]
https://github.com/bcgov/indy-catalyst/pull/343

**Comment by esune** [comment]
Done with #363
