### ISSUE TITLE
Create bcgov/indycat-agent repo

### ISSUE THREAD

**Issue by swcurran** [bcgov/indy-catalyst#270]
Do so with minimal changes, as if/when we move this to hyperledger/aries-python (or whatever). E.g. don't do any search/replace of names in the code.

Please retain the history, and make the minimal changes to enable continuing on as quickly as possible from this change.

Do change the links in documentation and scripts, if necessary (e.g. the removal of the "agent" folder - which I assume we will do?).

@WadeBarnes - please create the repo and provide appropriate permissions to those that need it.

**Comment by WadeBarnes** [comment]
Done:
https://github.com/bcgov/indycat-agent

**Comment by nrempel** [comment]
I'll be moving code over from indy-bcgov/catalyst as soon as some in-progress PRs on the agent are merged in.

**Comment by WadeBarnes** [comment]
https://github.com/bcgov/indy-email-verification/network/alerts

**Comment by WadeBarnes** [comment]
Plans changed, code and repo are here now; https://github.com/bcgov/aries-cloudagent-python
