### ISSUE TITLE
Add dependabot to IndyCatalyst CI/CD

### ISSUE THREAD

**Issue by swcurran** [bcgov/indy-catalyst#272]
Found on the rocketchat channels:

https://dependabot.com/docs/config-file/

It automatically detects new versions of dependencies and creates a pull request for them.
Also does security PRs

dependabot was acquired by Github and is now free

This would be really useful for all of our repos, so let's experiment with it in indy-catalyst and/or indycat-agent.  If it is good - we can expand it's use.

@WadeBarnes - please reassign if this should be a dev task.

FYI - @nrempel @esune @ianco @cywolf

**Comment by WadeBarnes** [comment]
Also thinking we can turn on the automated GitHub feature;
![image](https://user-images.githubusercontent.com/10504350/59714772-442f9800-91c7-11e9-844a-b3ae0997464f.png)

**Comment by WadeBarnes** [comment]
I turned on Automated security fixes on all of the VON repositories over which I have control.

**Comment by WadeBarnes** [comment]
Process:
Click on the Security tab for the repository.
Enable Automated security fixes.

![image](https://user-images.githubusercontent.com/10504350/59718349-db4c1e00-91ce-11e9-99a7-caa39187b7a6.png)
