### ISSUE TITLE
More flexible support for endpoints

### ISSUE THREAD

**Issue by andrewwhitehead** [bcgov/indy-catalyst#280]
- [ ] Support multiple `--endpoint` arguments and add them all to generated DIDDocs
- [ ] Support a `--hostname` parameter and automatically derive endpoint(s) based on the inbound transports supported

**Comment by swcurran** [comment]
@andrewwhitehead - is this done?  I think we have that and so can close this.  Or is this over and above what we have?  At minimum, if this is to stay open, we need to move it to ACA-Py.

**Comment by andrewwhitehead** [comment]
[Moved here](https://github.com/hyperledger/aries-cloudagent-python/issues/177)
