### ISSUE TITLE
Add optional logging of credential operations

### ISSUE THREAD

**Issue by andrewwhitehead** [bcgov/indy-catalyst#281]
Similar to the connection operation logging (log_state in ConnectionManager) which is now enabled by the `--debug-connections` flag, it would be beneficial to have a `--debug-credentials` flag to log extended information as credential-related operations are performed.

**Comment by swcurran** [comment]
@andrewwhitehead - another one for you to look at. Close? Move to ACA-Py?

**Comment by andrewwhitehead** [comment]
This one is in 0.3.0.
