### ISSUE TITLE
Support routing configuration in catalyst-demo-ui

### ISSUE THREAD

**Issue by andrewwhitehead** [bcgov/indy-catalyst#283]
Need to display the routing state on a connection record (when relevant) and support the `establish-inbound` method for pending connections, to nominate another connection as the inbound router.

**Comment by swcurran** [comment]
@andrewwhitehead - another one for you to look at. Close? Move to ACA-Py?

**Comment by andrewwhitehead** [comment]
It's not really an ACApy issue, it relates to the 'AgentBook' UI. Could be created on that repo but then nobody would see it.

**Comment by swcurran** [comment]
Closing issue. Agentbook is currently not under active development.
