### ISSUE TITLE
New repo for indy cat agent template

### ISSUE THREAD

**Issue by ianco** [bcgov/indy-catalyst#287]
Please create a new github repository for:

bcgov/indy-catalyst-agent-template

I'll confirm the repo name with @swcurran

**Comment by WadeBarnes** [comment]
Name confirmed `indy-catalyst-agent`

**Comment by WadeBarnes** [comment]
Created a uninitialized repo here; https://github.com/bcgov/indy-catalyst-agent

**Comment by WadeBarnes** [comment]
Over to @ianco to populate.
