### ISSUE TITLE
Implement credential verification with Aries agent

### ISSUE THREAD

**Issue by ianco** [bcgov/indy-catalyst#298]
Implement proofs/verification with new Aries agent
- holder agent must establish a connection with self
- integrate with "verify" web service called by web UI

**Comment by nrempel** [comment]
addressed in https://github.com/bcgov/indy-catalyst/pull/348

**Comment by esune** [comment]
Once [this PR](https://github.com/hyperledger/indy-sdk/pull/1893) is merged in indy-sdk we will be able to enable full verification of vredentials.

**Comment by esune** [comment]
@nrempel did you get any more news about the PR that fixes the multi-constraint proof verification issue?
