### ISSUE TITLE
Attributes not displaying correctly on OrgBook UI

### ISSUE THREAD

**Issue by ianco** [bcgov/indy-catalyst#302]
... when loading with new Aries agent

**Comment by esune** [comment]
It looks like there was a filter that was applied when retrieving attributes that would exclude anything that was not defined in a schema that had "Registration" as description. Removing the filter seems to fix the issue.

I applied the same change to both indy-catalyst and TheOrgBook:
- https://github.com/bcgov/indy-catalyst/pull/316
- https://github.com/bcgov/TheOrgBook/pull/834
