### ISSUE TITLE
The value -1 is outside the acceptable range of [0,2147483647], parameter name: value'

### ISSUE THREAD

**Issue by ldrollin** [bcgov/indy-catalyst#320]
Visual Studio Community 2019 Version 16.2.0 

When adding a new controller "Web API 2 Controller - Empty" I receive this error after naming the controller:

'The value -1 is outside the acceptable range of [0,2147483647], parameter name: value'

First, What does that mean?

Second, how do I fix this error?

**Comment by ianco** [comment]
Can you provide a bit more context around what you are doing and where you are seeing this error?

**Comment by ldrollin** [comment]
I essentially following the Autodesk Forge Tutorial and got to this step (https://learnforge.autodesk.io/#/oauth/2legged/net) in the process when I received the error.

**Comment by ianco** [comment]
Sorry I'm not familiar with this tutorial or how the error would relate to Indy Catalyst.  I haven't seen this error before.

**Comment by ldrollin** [comment]
Could you recommend me to someone that does?

I've scoured the help forums of both visual studio and github, and the only other one that mentions the same error as mine doesn't have a solution either.

I cannot create a web api controller without figuring out what this error even means.

**Comment by ianco** [comment]
Try asking the authors of the tutorial, I notice there is a link at the bottom of the page:

"Questions on this tutorial? Ask on Stackoverflow or email us"

**Comment by ldrollin** [comment]
Someone has already asked the same error question. 

I've added mine to the pool of questions, but no one has solution for the other guy yet either.
