### ISSUE TITLE
Add updates made to TOB Timeline are made to ICOB

### ISSUE THREAD

**Issue by ianco** [bcgov/indy-catalyst#359]
Ensure any commits to TOB are also applied to ICOB (https://github.com/bcgov/indy-catalyst).

Updates were last sync'ed on July 26 so any TOB updates since then must be manually applied to ICOB.

Since the ICOB structure is somewhat different than TOB, this might take a bit of work, but you'll have to get into it to figure out how much.

**Comment by swcurran** [comment]
@seanadipose Please plan on doing this after the Identity Kit work that was discussed yesterday.
