### ISSUE TITLE
Web Hooks - sort out required attributes for web hook registration/subscription services

### ISSUE THREAD

**Issue by ianco** [bcgov/indy-catalyst#383]
For type 'New', doesn't require a topic id

For type 'Topic', requires a topic id but not a credential type

For type 'Stream', requires both a topic id and credential type

For registration, target_url and hook_token are optional

For subscription, target url and hook_token are:
- optional, if they have been provided in the registration
- required, if they were *not* provided in the registration

When sending web hooks, inspect both the registration and subscription to determine the target_url and hook_token

**Comment by swcurran** [comment]
@ianco - I've added this to the epic we're using for tracking tasks to be completed before we go live with ICOB OrgBook BC.  I'm assuming this is needed before then, but let me know if not.

**Comment by esune** [comment]
See [this PR](https://github.com/bcgov/indy-catalyst/pull/396).
