### ISSUE TITLE
Re-organize folder structure

### ISSUE THREAD

**Issue by nrempel** [bcgov/indy-catalyst#408]
Consolidate "starter-kits" directory and other paths.

**Comment by WadeBarnes** [comment]
Make sure the associated PR gets assigned to me before it is merged so I can make any necessary changes to the OpenShift builds.

**Comment by nrempel** [comment]
Will do. I'll make sure you're tagged on the review.

**Comment by nrempel** [comment]
Pull request opened here https://github.com/bcgov/indy-catalyst/pull/413

**Comment by esune** [comment]
@nrempel #397 is the issue I mentioned today about the API not being able to handle large datasets.

I don't think this issue is meant to track the API refactoring, and I could not find a logged issue for that purpose so just bringing this up for awareness.
