### ISSUE TITLE
EAO  OpenShift deployment

### ISSUE THREAD

**Issue by ianco** [bcgov/indy-catalyst#97]

**Comment by esune** [comment]
OpenShift deployments have been completed and deployments are up and running in our test environment.

The last thing to figure out is how to apply the bcgov theme with the new repository structure.

**Comment by esune** [comment]
@WadeBarnes: "parking" the issue in Review/QA until we have time to look at why these deployments seem to require different settings than the other environments, or deem this step unnecessary.
